Issue 1 create entry
louiewhitz/code-journal-user-can-create-an-entry pull request #6
Opened 2022-06-01 22:11 UTC by louiewhitz

![Screen Shot 2022-06-01 at 2 57 34 PM](https://user-images.githubusercontent.com/99847558/171510165-f0befcb9-8ab2-41bb-9784-8558ed86a03d.png)
![Screen Shot 2022-06-01 at 2 56 12 PM](https://user-images.githubusercontent.com/99847558/171510224-a0fc8f01-ea70-41a5-b923-e0fd45cb69cc.png)
![Screen Shot 2022-06-01 at 3 11 05 PM](https://user-images.githubusercontent.com/99847558/171510394-84de56cc-854f-4df8-9f59-54c9f5cca09b.png)

2022-06-01 23:25 UTC, louiewhitz commented
![Screen Shot 2022-06-01 at 4 17 48 PM](https://user-images.githubusercontent.com/99847558/171517570-ab59ca9c-5ffb-4e9d-8718-b097976ae7fe.png)
![Screen Shot 2022-06-01 at 4 19 58 PM](https://user-images.githubusercontent.com/99847558/171517600-a4cfe4ac-617c-481d-9ac5-f1bf3f64a370.png)

2022-06-01 23:30 UTC, codingcodymiller requested changes

2022-06-01 23:30 UTC, codingcodymiller commented on css/styles.css
> +  top: 426px;
This should get removed, this element doesn't seem to be being positioned in any way, so this will have no effect.

2022-06-01 23:30 UTC, codingcodymiller commented on css/styles.css
> +  top: 623px;
This should get removed, this element doesn't seem to be being positioned in any way, so this will have no effect.

2022-06-01 23:30 UTC, codingcodymiller commented on css/styles.css
> +  top: 706px;
This should get removed, this element doesn't seem to be being positioned in any way, so this will have no effect.

2022-06-01 23:30 UTC, codingcodymiller commented on js/main.js
> +$newImage.addEventListener('change', changeUrl);
You should use the `input` event rather than `change`.

2022-06-01 23:30 UTC, codingcodymiller commented on js/main.js
> +    nextEntryId: data['nextEntryId']
You can just use dot notation. Also, `nextEntryId` is not an appropriate name for this property, since it is storing this entry's id, not the next entry id to use. You should name this property `entryId`

2022-06-01 23:30 UTC, codingcodymiller commented on js/main.js
> +  data['entries'].push(obj);
Use dot notation

2022-06-01 23:30 UTC, codingcodymiller commented on js/main.js
> +  data['nextEntryId'] += 1;
Use dot notation

2022-06-01 23:54 UTC, louiewhitz commented
![Screen Shot 2022-06-01 at 4 52 18 PM](https://user-images.githubuse
![Screen Shot 2022-06-01 at 4 52 46 PM](https://user-images.githubusercontent.com/99847558/171520067-167092c6-1ddd-4c9d-bf92-a0adca420e58.png)
rcontent.com/99847558/171520062-55cb5c4b-20cf-4f27-a403-13d44727185e.png)

2022-06-02 00:00 UTC, codingcodymiller requested changes

2022-06-02 00:00 UTC, codingcodymiller commented on js/main.js
> +    nextEntry: data.nextEntryId
`entryId`, not `nextEntry`. This has the same issue as the last name, it isn't accurate

2022-06-02 00:00 UTC, codingcodymiller commented on js/main.js
> +  data.entries.push(obj);
You should be adding this object to the beginning of the array, not the end.

2022-06-02 00:00 UTC, codingcodymiller commented on js/main.js
>  }
All localStorage-related code should be in the `data.js` file, where the data model is that you are preserving.

2022-06-02 00:00 UTC, codingcodymiller commented on js/main.js
>    $image.setAttribute('src', 'images/placeholder-image-square.jpg');
These things should be happening in the submit event handler. You don't want to reset the form and the image right before the page unloads, you want to do it when an entry is submitted.

2022-06-02 00:14 UTC, louiewhitz commented
![Screen Shot 2022-06-01 at 5 12 12 PM](https://user-images.githubusercontent.com/99847558/171521851-135489ed-acfb-4378-a51a-fc34ae19f3c6.png)
![Screen Shot 2022-06-01 at 5 12 46 PM](https://user-images.githubusercontent.com/99847558/171521860-0afe6a4c-8706-4f70-8473-ae08b6085b20.png)

2022-06-02 00:17 UTC, codingcodymiller requested changes

2022-06-02 00:17 UTC, codingcodymiller commented on js/data.js
> +  entryId: 1
This one was correctly named before, its value represents the next entry id to use. You only needed to change the name of the property you created on the individual entry objects.

2022-06-02 00:17 UTC, codingcodymiller commented on js/main.js
> +    nextEntry: data.nextEntryId
This property is still named `nextEntry`, it should be changed to `entryId`

2022-06-02 00:29 UTC, codingcodymiller requested changes

2022-06-02 00:29 UTC, codingcodymiller commented on js/main.js
> +function beforeUnload(event) {
This function needs to be deleted as well as the beforeunload event listener, you already have this in the data.js file

2022-06-02 00:36 UTC, codingcodymiller approved these changes

2022-06-09 03:57 UTC, merged